CREATE TABLE spaces
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)   NOT NULL,
    type        VARCHAR(30)    NOT NULL,
    capacity    INTEGER        NOT NULL,
    location    VARCHAR(150)   NOT NULL,
    hourly_rate NUMERIC(10, 2) NOT NULL,
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    version     BIGINT         NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ    NOT NULL,
    updated_at  TIMESTAMPTZ    NOT NULL,
    CONSTRAINT ck_spaces_type CHECK (type IN ('MEETING_ROOM', 'DESK', 'PRIVATE_OFFICE')),
    CONSTRAINT ck_spaces_capacity CHECK (capacity > 0),
    CONSTRAINT ck_spaces_hourly_rate CHECK (hourly_rate > 0)
);

-- Names are unique among active spaces only: a soft-deleted space frees its name.
CREATE UNIQUE INDEX uk_spaces_name_active ON spaces (LOWER(name)) WHERE active;

CREATE INDEX ix_spaces_type ON spaces (type) WHERE active;
