-- Dynamic RBAC: roles are managed through the API; permissions are a fixed catalog checked by the code.
CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(200) NOT NULL
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(200) NOT NULL,
    system      BOOLEAN      NOT NULL DEFAULT FALSE,
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by  VARCHAR(150) NOT NULL DEFAULT 'system',
    updated_by  VARCHAR(150) NOT NULL DEFAULT 'system'
);

CREATE UNIQUE INDEX uk_roles_name ON roles (UPPER(name));

CREATE TABLE role_permissions
(
    role_id       BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions (id),
    PRIMARY KEY (role_id, permission_id)
);

INSERT INTO permissions (code, description)
VALUES ('SPACE_READ', 'Consultar espacios'),
       ('SPACE_WRITE', 'Crear, modificar y desactivar espacios'),
       ('RESERVATION_CREATE', 'Crear y cancelar reservas propias'),
       ('RESERVATION_READ_OWN', 'Consultar reservas propias'),
       ('RESERVATION_READ_ALL', 'Consultar todas las reservas'),
       ('RESERVATION_MANAGE_ALL', 'Gestionar cualquier reserva'),
       ('REPORT_READ', 'Consultar reportes de ocupación'),
       ('USER_MANAGE', 'Crear, consultar y bloquear usuarios'),
       ('RBAC_MANAGE', 'Crear roles y asignar permisos'),
       ('METRICS_READ', 'Consultar métricas de la aplicación');

INSERT INTO roles (name, description, system)
VALUES ('ADMIN', 'Administrador con todos los permisos', TRUE),
       ('USER', 'Usuario que reserva espacios', TRUE);

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         CROSS JOIN permissions p
WHERE r.name = 'ADMIN';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.code IN ('SPACE_READ', 'RESERVATION_CREATE', 'RESERVATION_READ_OWN')
WHERE r.name = 'USER';

-- Users move from the role enum column to a reference to roles, and gain an account status.
ALTER TABLE users ADD COLUMN role_id BIGINT REFERENCES roles (id);
UPDATE users u SET role_id = (SELECT r.id FROM roles r WHERE r.name = u.role);
ALTER TABLE users ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE users DROP COLUMN role;
CREATE INDEX ix_users_role ON users (role_id);

ALTER TABLE users ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED'));
