-- needed for the no-overlap constraint below
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE reservations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id        BIGINT         NOT NULL REFERENCES spaces (id),
    user_id         BIGINT         NOT NULL REFERENCES users (id),
    start_at        TIMESTAMPTZ    NOT NULL,
    end_at          TIMESTAMPTZ    NOT NULL,
    status          VARCHAR(30)    NOT NULL,
    total_amount    NUMERIC(10, 2) NOT NULL,
    idempotency_key VARCHAR(64)    NOT NULL,
    cancelled_at    TIMESTAMPTZ,
    version         BIGINT         NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ    NOT NULL,
    updated_at      TIMESTAMPTZ    NOT NULL,
    created_by      VARCHAR(150)   NOT NULL,
    updated_by      VARCHAR(150)   NOT NULL,
    CONSTRAINT ck_reservations_status CHECK (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_reservations_period CHECK (end_at > start_at),
    CONSTRAINT ck_reservations_amount CHECK (total_amount >= 0),
    CONSTRAINT uk_reservations_idempotency UNIQUE (user_id, idempotency_key),
    -- blocks double booking even when two requests hit at the same time
    CONSTRAINT ex_reservations_no_overlap EXCLUDE USING gist (
        space_id WITH =,
        tstzrange(start_at, end_at, '[)') WITH &&
        ) WHERE (status <> 'CANCELLED')
);

CREATE INDEX ix_reservations_user ON reservations (user_id, start_at DESC);
CREATE INDEX ix_reservations_space ON reservations (space_id, start_at);
