ALTER TABLE reservations ADD COLUMN payment_reference VARCHAR(64);

-- one row per call to the provider, approved or not
CREATE TABLE payment_attempts
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id     BIGINT         NOT NULL REFERENCES reservations (id),
    method_type        VARCHAR(30)    NOT NULL,
    masked_instrument  VARCHAR(16)    NOT NULL,
    idempotency_key    VARCHAR(64)    NOT NULL,
    amount             NUMERIC(10, 2) NOT NULL,
    outcome            VARCHAR(30)    NOT NULL,
    decline_reason     VARCHAR(30),
    provider_reference VARCHAR(64),
    duration_ms        BIGINT         NOT NULL,
    created_at         TIMESTAMPTZ    NOT NULL,
    updated_at         TIMESTAMPTZ    NOT NULL,
    created_by         VARCHAR(150)   NOT NULL,
    updated_by         VARCHAR(150)   NOT NULL,
    CONSTRAINT ck_payment_attempts_outcome CHECK (outcome IN ('APPROVED', 'DECLINED', 'UNAVAILABLE'))
);

CREATE INDEX ix_payment_attempts_reservation ON payment_attempts (reservation_id, created_at);
